In [39]:
import pandas as pd
import numpy as np
import csv
import ast
import matplotlib.pyplot as plt

In [4]:
gs_csv = "gs_outputs/gs_authorlist_publications_notitles.csv"
scival_csv = "scival_outputs/scival_authorlist_publications_withdoccounts.csv"

In [5]:
gs_df = pd.read_csv(gs_csv)
scival_df = pd.read_csv(scival_csv)

In [6]:
print(gs_df.head)
print(scival_df.head)

<bound method NDFrame.head of                             Name    Scholar ID  Document Count  Cited by  \
0                  Tim H. Murphy  qJjM8hkAAAAJ             239     21139   
1            Annie Vogel Ciernia  XAGfOIIAAAAJ              44      1964   
2                 Brian MacVicar  Sx3420cAAAAJ             217     22082   
3           Fidel Vila-Rodriguez  VynxFpEAAAAJ             263      5626   
4                  Shernaz Bamji  C832lNEAAAAJ              59      5306   
5                      Lara Boyd  yutn3mwAAAAJ             356     15074   
6                  Paul Pavlidis  ataejQQAAAAJ             245     17627   
7              Martin J. McKeown  cBAT2tQAAAAJ             369     16443   
8   A Jon Stoessl OR jon Stoessl  KnhWIqwAAAAJ             449     30713   
9                  Peter Cripton  hm6fJTkAAAAJ             284      7678   
10               Jason S. Snyder  B6Fe4-4AAAAJ              39      6034   
11              Wolfram Tetzlaff  HgUvr-IAAAAJ            

In [42]:
def get_coauthor_matrix(df):
    names = df.loc[:,"Name"]
    coauthor_matrix = np.zeros((names.size, names.size))

    for idx, author in df.iterrows():
        auth_name = author["Name"]
        row = names[names == auth_name].index[0]
        try:
            coauthors = ast.literal_eval(author["Coauthors"]) #get coauthors
            if len(coauthors) == 0: print(auth_name, "has no coauthors")
            for coauthor in coauthors.keys():
                num_publications = coauthors[coauthor]
                col = names[names == coauthor].index[0]
                coauthor_matrix[col][row] += num_publications

        except:
            print(auth_name, "has no coauthors")
    
    print("\n")
    return coauthor_matrix

In [43]:
scival_coauthor_matrix = get_coauthor_matrix(scival_df)
gs_coauthor_matrix = get_coauthor_matrix(gs_df)     



Annie Vogel-Ciernia has no coauthors
Mark S. Cembrowski has no coauthors
Michael J. Gordon has no coauthors
Manu S. Madhav has no coauthors
Brian D. Fisher has no coauthors
Emily Lauren Sylwestrak has no coauthors


Michael Gordon has no coauthors
Manu S Madhav has no coauthors
Emily Sylwestrak has no coauthors




In [44]:
print(scival_coauthor_matrix)
print(gs_coauthor_matrix)



[[0. 0. 1. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 3. ... 0. 9. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [3. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [9. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
